### ISSUE TITLE
error

### ISSUE THREAD

**Issue by noobbeast** [syberia-project/platform_build#5]
FAILED: Package target files: /home/noobbeast/gunung/out/target/product/begonia/obj/PACKAGING/target_files_intermediates/syberia_begonia-target_files-eng.nobody.zip
Outputs: /home/noobbeast/gunung/out/target/product/begonia/obj/PACKAGING/target_files_intermediates/syberia_begonia-target_files-eng.nobody.zip
Error: exited with code: 1
Command: /bin/bash -c "(rm -rf /home/noobbeast/gunung/out/target/product/begonia/obj/PACKAGING/target_files_intermediates/syberia_begonia-target_files-eng.nobody.zi>
Output:
ls: /home/noobbeast/gunung/out/target/product/begonia/data: No such file or directory
2022-02-05 20:12:56 - common.py - WARNING : Failed to read SYSTEM/etc/build.prop
2022-02-05 20:12:56 - common.py - WARNING : Failed to read VENDOR/etc/build.prop
2022-02-05 20:12:56 - common.py - WARNING : Failed to read PRODUCT/etc/build.prop
2022-02-05 20:12:56 - common.py - WARNING : Failed to read PRODUCT/build.prop
2022-02-05 20:12:56 - common.py - WARNING : Failed to read SYSTEM_EXT/etc/build.prop
2022-02-05 20:12:56 - common.py - WARNING : Failed to read SYSTEM_EXT/build.prop
2022-02-05 20:12:56 - common.py - WARNING : Failed to read ODM/etc/build.prop
2022-02-05 20:12:56 - common.py - WARNING : Failed to read ODM/build.prop
2022-02-05 20:12:56 - common.py - WARNING : Failed to read VENDOR_DLKM/etc/build.prop
2022-02-05 20:12:56 - common.py - WARNING : Failed to read VENDOR_DLKM/build.prop
2022-02-05 20:12:56 - common.py - WARNING : Failed to read ODM_DLKM/etc/build.prop
2022-02-05 20:12:56 - common.py - WARNING : Failed to read ODM_DLKM/build.prop
2022-02-05 20:12:56 - common.py - WARNING : Failed to read IMAGES/boot.img
2022-02-05 20:12:56 - common.py - WARNING : Can't find META/ab_partitions.txt
2022-02-05 20:13:00 - common.py - WARNING : Failure running ['imgdiff', '-b', '/home/noobbeast/gunung/out/target/product/begonia/obj/PACKAGING/target_files_intermed>
imgdiff W 02-05 20:13:00 670725 670725 imgdiff.cpp:1435] Failed to reconstruct target deflate chunk 3 []; treating as normal
imgdiff E 02-05 20:13:00 670725 670725 imgdiff.cpp:1390] Failed to set bonus data

Traceback (most recent call last):
  File "/home/noobbeast/gunung/out/host/linux-x86/bin/make_recovery_patch/internal/stdlib/runpy.py", line 174, in _run_module_as_main
  File "/home/noobbeast/gunung/out/host/linux-x86/bin/make_recovery_patch/internal/stdlib/runpy.py", line 72, in _run_code
  File "/home/noobbeast/gunung/out/host/linux-x86/bin/make_recovery_patch/__main__.py", line 12, in <module>
  File "/home/noobbeast/gunung/out/host/linux-x86/bin/make_recovery_patch/internal/stdlib/runpy.py", line 174, in _run_module_as_main
  File "/home/noobbeast/gunung/out/host/linux-x86/bin/make_recovery_patch/internal/stdlib/runpy.py", line 72, in _run_code
  File "/home/noobbeast/gunung/out/host/linux-x86/bin/make_recovery_patch/make_recovery_patch.py", line 73, in <module>
  File "/home/noobbeast/gunung/out/host/linux-x86/bin/make_recovery_patch/make_recovery_patch.py", line 69, in main
  File "/home/noobbeast/gunung/out/host/linux-x86/bin/make_recovery_patch/common.py", line 3528, in MakeRecoveryPatch
  File "/home/noobbeast/gunung/out/host/linux-x86/bin/make_recovery_patch/make_recovery_patch.py", line 67, in output_sink
TypeError: argument 1 must be string or buffer, not None

**Comment by TheStrechh** [comment]
fixed?
